PATH:
  ROOT_PATH: "/home/apie/projects/AIC20-MTMC/dataset/AIC20_T3"
  RESNET_PRETRAIN_MODEL_PATH: "/home/apie/projects/AIC20-MTMC/weights/resnet50-19c8e357.pth"
  REID_MODEL_PATH: "/home/apie/projects/AIC20-MTMC/weights/resnet50_model_t2.pth"
  DHN_PRETRAIN_MODEL_PATH: "/home/apie/projects/AIC20-MTMC/weights/DHN.pth"

DEVICE:
  TYPE: "cuda" 
  GPU: 1