PATH:
  ROOT_PATH: "/home/apie/projects/AIC20-MTMC/dataset/AIC20_T3"
  RESNET_PRETRAIN_MODEL_PATH: "/home/apie/projects/AIC20-MTMC/weights/resnet50-19c8e357.pth"
  REID_MODEL_PATH: "/home/apie/projects/AIC20-MTMC/weights/resnet50_model_t2.pth"
  DHN_PRETRAIN_MODEL_PATH: "/home/apie/projects/AIC20-MTMC/weights/DHN.pth"

MODEL:
  NAME: "dhn"
  DEVICE: "cuda"
  CUDA: 1
  BI_DIRECTION: True
  ELEMENT_DIM: 1
  HIDDEN_DIM: 256
  TARGET_SIZE: 1
  OUTPUT_DIR: "/home/apie/projects/AIC20-MTMC/dhn_baseline/export_dir/aic20_t3"

DATASETS:
  NAME: 'aic20_t3'

DATALOADER:
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  OPTIMIZER_NAME: 'Adam'
  MAX_EPOCHS: 20
  BASE_LR: 0.0003
  BIAS_LR_FACTOR: 1
  WEIGHT_DECAY: 0.05
  WEIGHT_DECAY_BIAS: 0.0005
  IMS_PER_BATCH: 1

  STEPS: [40, 70]
  GAMMA: 0.1

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 2000
  WARMUP_METHOD: 'linear'

  CHECKPOINT_PERIOD: 5
  LOG_PERIOD: 100
  EVAL_PERIOD: 20

TEST:
  IMS_PER_BATCH: 1