PATH:
  ROOT_PATH: "/home/apie/projects/AIC20-MTMC/dataset/AIC20_T3"
  INPUT_PATH: "/home/apie/projects/AIC20-MTMC/dataset/AIC20_T3/test"

DEVICE:
  TYPE: "cuda"
  GPU: 1

REID:
  NAME: "t2t3"
  RESNET_PRETRAIN_MODEL_PATH: "/home/apie/projects/AIC20-MTMC/weights/resnet50-19c8e357.pth"
  MODEL_PATH: "/home/apie/projects/AIC20-MTMC/weights/resnet50_model_t2t3.pth"
  PIXEL_MEAN: [0.485, 0.456, 0.406]
  PIXEL_STD: [0.229, 0.224, 0.225]
  SIZE_TEST: [256,256]
  LAST_STRIDE: 1

MTMC:
<<<<<<< HEAD
  MODEL_PATH: "/home/apie/projects/AIC20-MTMC/weights/model_mtmc_150 copy.pth"
  APPEARANCE_DIM: 4096
  HIDDEN_DIM: 6
  PHYSIC_DIM: 5
=======
  MODEL_PATH: "/home/apie/projects/AIC20-MTMC/weights/mtmc_model_t2t3_5.pth"
  HIDDEN_DIM: 4101
>>>>>>> parent of 2349a86... add expected time limit
  TS_MIN: [0.000, 0.000]
  TS_MAX: [208.0, 205.0]
  GPS_MIN: [0.000, 0.000, 0.000]
  GPS_MAX: [0.000905503, 0.000890009, 0.016692804]
