PATH:
  ROOT_PATH: "/home/apie/projects/AIC20-MTMC/dataset/AIC20_T3"

MODEL:
  NAME: "mtmc"
  DEVICE: "cuda"
  CUDA: 1
  HIDDEN_DIM: 256
  OUTPUT_DIR: "/home/apie/projects/AIC20-MTMC/mt_tracker/export_dir/mtmc"

DATASETS:
  NAME: 'mtmc'

DATALOADER:
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  OPTIMIZER_NAME: 'Adam'
  MAX_EPOCHS: 20
  BASE_LR: 0.0003
  BIAS_LR_FACTOR: 1
  WEIGHT_DECAY: 0.05
  WEIGHT_DECAY_BIAS: 0.0005
  IMS_PER_BATCH: 1

  STEPS: [40, 70]
  GAMMA: 0.1

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 2000
  WARMUP_METHOD: 'linear'

  CHECKPOINT_PERIOD: 5
  LOG_PERIOD: 100
  EVAL_PERIOD: 20
