PATH:
  ROOT_PATH: "/home/apie/projects/AIC20-MTMC/dataset/AIC20_T3"

MODEL:
  NAME: "mtmc"
  DEVICE: "cuda"
  CUDA: 2
  HIDDEN_DIM: 6
  APPEARANCE_DIM: 4096
  PHYSIC_DIM: 5
  OUTPUT_DIR: "/home/apie/projects/AIC20-MTMC/mt_tracker/export_dir/mtmc-3"
  TEST_MODEL: "/home/apie/projects/AIC20-MTMC/mt_tracker/export_dir/mtmc-3/model_mtmc_150.pth"

DATASETS:
  NAME: 'mtmc'

DATALOADER:
  NUM_INSTANCE: 4
  NUM_WORKERS: 2

INPUT:
  TS_MIN: [0.000, 0.000]
  TS_MAX: [208.0, 205.0]
  GPS_MIN: [0.000, 0.000, 0.000]
  GPS_MAX: [0.000905503, 0.000890009, 0.016692804]

SOLVER:
  OPTIMIZER_NAME: 'Adam'
  MAX_EPOCHS: 150
  BASE_LR: 0.01
  BIAS_LR_FACTOR: 1
  WEIGHT_DECAY: 0.05
  WEIGHT_DECAY_BIAS: 0.0005
  IMS_PER_BATCH: 64

  STEPS: [40, 70]
  GAMMA: 0.1

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 4000
  WARMUP_METHOD: 'linear'

  CHECKPOINT_PERIOD: 50
  LOG_PERIOD: 10
  EVAL_PERIOD: 50
