PATH:
  ROOT_PATH: "/home/apie/projects/AIC20-MTMC/dataset/AIC20_T3"

MODEL:
  NAME: "mtmc"
  DEVICE: "cuda"
  CUDA: 2
  HIDDEN_DIM: 4101
  OUTPUT_DIR: "/home/apie/projects/AIC20-MTMC/mt_tracker/export_dir/mtmc-3"
  TEST_MODEL: "/home/apie/projects/AIC20-MTMC/mt_tracker/export_dir/mtmc-3/mtmc_model_5.pth"

DATASETS:
  NAME: 'mtmc'

DATALOADER:
  NUM_INSTANCE: 4
  NUM_WORKERS: 2

INPUT:
  TS_STD: [38.03783, 38.19534]
  TS_MEAN: [27.26076, 25.96027]
  GPS_STD: [0.00013765, 0.00013720, 0.00057203]
  GPS_MEAN: [0.000005636, 0.000005611, 0.000002973]

SOLVER:
  OPTIMIZER_NAME: 'Adam'
  MAX_EPOCHS: 150
  BASE_LR: 0.01
  BIAS_LR_FACTOR: 1
  WEIGHT_DECAY: 0.05
  WEIGHT_DECAY_BIAS: 0.0005
  IMS_PER_BATCH: 64

  STEPS: [40, 70]
  GAMMA: 0.1

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 4000
  WARMUP_METHOD: 'linear'

  CHECKPOINT_PERIOD: 50
  LOG_PERIOD: 10
  EVAL_PERIOD: 50
